version: '2.2'

services:

  users-db:
    container_name: users-db
    build: ./project/db
    ports:
      - 5435:5432 # expose ports - HOST:CONTAINER
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: exit 0

  kanji-db:
    container_name: kanji-db
    build: ./project/db
    ports:
      - 5436:5432 # expose ports - HOST:CONTAINER
    environment:
      - POSTGRES_USER=jmdictdb
      - POSTGRES_PASSWORD=your_password
      - POSTGRES_DB=jmdict
    healthcheck:
      test: exit 0

  users-service:
    container_name: users-service
    build: ./
    volumes:
      - '.:/usr/src/app'
    ports:
      - 5001:5000 # expose ports - HOST:CONTAINER
    environment:
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test
      - KANJI_DATABASE_URL=postgres://jmdictdb:your_password@kanji-db:5432/jmdict
      - KANJI_DATABASE_TEST_URL=postgres://jmdictdb:your_password@kanji-db:5432/jmdict
    depends_on:
      users-db:
        condition: service_healthy
      kanji-db:
        condition: service_healthy
    links:
      - users-db
      - kanji-db
