version: '2.2'

services:

  users-db:
    container_name: users-db
    build: ./project/db
    ports:
      - 5435:5432 # expose ports - HOST:CONTAINER
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: exit 0

  users-service:
    container_name: users-service
    build: ./
    ports:
      - 5001:5000 # expose ports - HOST:CONTAINER
    environment:
      - APP_SETTINGS=project.config.ProductionConfig
      - DATABASE_URL=postgres://jmdictdb:your_password@users-db:5432/jmdict
      - DATABASE_TEST_URL=postgres://jmdictdb:your_password@users-db:5432/jmdict
    depends_on:
      users-db:
        condition: service_healthy
    links:
      - users-db
